ui:
  default_width: 450
inputs_def:
  - handle: jsonPath
    description: Input
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  []
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
title: Json file preview
icon: ":carbon:json:"
