ui:
  default_width: 450
inputs_def:
  - handle: jsonPath
    description: Input
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        filters:
          - name: JSON
            extensions:
              - json
              - jsonc
              - json5
              - geojson
              - geo.json
outputs_def:
  []
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
title: JSON file preview
icon: ":carbon:json:"
