executor:
  name: nodejs
  options:
    entry: index.ts
    spawn: false
inputs_def:
  - handle: image_path
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        filters:
          - name: PNG
            extensions:
              - png
              - apng
          - name: JPEG
            extensions:
              - jpg
              - jpeg
              - jfif
              - pjpeg
              - pjp
          - name: WebP
            extensions:
              - webp
          - name: GIF
            extensions:
              - gif
          - name: AVIF
            extensions:
              - avif
          - name: BMP
            extensions:
              - bmp
          - name: ICO
            extensions:
              - ico
              - cur
          - name: TIFF
            extensions:
              - tif
              - tiff
outputs_def:
  []
title: Image preview
icon: ":carbon:image-search:"
