inputs_def:
  - handle: binary
    description: Input
    json_schema:
      contentMediaType: oomol/bin
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Binary Image preview
icon: ":fa6-solid:file-image:"
