inputs_def:
  - handle: text
    description: Input
    json_schema:
      type: string
      ui:widget: text
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Markdown preview
icon: ":fa6-solid:note-sticky:"
