inputs_def:
  - handle: audio_path
    description: Input
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Audio preview
