inputs_def:
  - handle: audio_path
    description: Input
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: index.ts
    spawn: false
title: Audio preview
icon: ":carbon:document-audio:"
