inputs_def:
  - handle: video_path
    description: Input
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        filters:
          - name: MP4
            extensions:
              - mp4
              - m4v
          - name: WebM
            extensions:
              - webm
          - name: HLS
            extensions:
              - .m3u8
          - name: MOV
            extensions:
              - mov
              - qt
              - mqv
          - name: Ogg
            extensions:
              - ogv
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: index.ts
    spawn: false
title: Video preview
icon: ":carbon:video-player:"
