inputs_def:
  - handle: images
    description: Input
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
        ui:options:
          filters:
            - name: PNG
              extensions:
                - png
                - apng
            - name: JPEG
              extensions:
                - jpg
                - jpeg
                - jfif
                - pjpeg
                - pjp
            - name: WebP
              extensions:
                - webp
            - name: GIF
              extensions:
                - gif
            - name: AVIF
              extensions:
                - avif
            - name: BMP
              extensions:
                - bmp
            - name: ICO
              extensions:
                - ico
                - cur
            - name: TIFF
              extensions:
                - tif
                - tiff
outputs_def:
  - handle: images
    description: Output
    json_schema:
      type: array
      items:
        type: string
        ui:widget: file
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: index.ts
    spawn: false
title: Images preview
icon: ":carbon:image-copy:"
