inputs_def:
  - handle: html
    description: Input
    json_schema:
      type: string
      ui:widget: text
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: index.ts
    spawn: false
title: HTML preview
icon: ":carbon:earth-filled:"
