ui:
  default_width: 450
inputs_def:
  - handle: jsonString
    description: Input
    json_schema:
      type: string
outputs_def:
  []
executor:
  name: nodejs
  options:
    entry: main.ts
    spawn: false
icon: ":carbon:json:"
title: Json string preview
