inputs_def:
  - handle: video_path
    description: Input
    json_schema:
      type: string
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: main.py
title: Video preview
