inputs_def:
  - handle: text
    description: Input
    json_schema:
      type: string
      ui:widget: text
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: index.ts
    spawn: false
title: Markdown preview
icon: ":fa6-solid:note-sticky:"
