inputs_def:
  - handle: file_path
    description: Input
    json_schema:
      type: string
      ui:widget: file
outputs_def:
  - handle: text
    description: Output
    json_schema:
      type: string
ui:
  default_width: 450
executor:
  name: python
  options:
    spawn: false
    entry: __init__.py
title: markdown_file_preview
icon: ":fa6-solid:file-lines:"
