inputs_def:
  - handle: file_path
    description: Input
    json_schema:
      type: string
      ui:widget: file
      ui:options:
        filters:
          - name: Markdown
            extensions:
              - md
              - markdown
              - mdown
outputs_def:
  []
ui:
  default_width: 450
executor:
  name: nodejs
  options:
    entry: index.ts
    spawn: false
title: Markdown file preview
icon: ":carbon:document-attachment:"
